#!/bin/bash
# install essential packages
echo =-=-=-=-=-=-=-=-=-=-=-=-=-=-=
echo Installing essential packages
echo =-=-=-=-=-=-=-=-=-=-=-=-=-=-=
echo Installing git..
pacman --noconfirm --needed -S git > /dev/null 2>&1
echo Installing Network Manager...
pacman --noconfirm --needed -S networkmanager > /dev/null 2>&1
systemctl enable NetworkManager > /dev/null 2>&1
echo Installing dosfstools...
pacman --noconfirm --needed -S dosfstools > /dev/null 2>&1
echo Installing mtools...
pacman --noconfirm --needed -S mtools > /dev/null 2>&1
echo Installing gptfdisk...
pacman --noconfirm --needed -S gptfdisk > /dev/null 2>&1
echo Installing fatresize...
pacman --noconfirm --needed -S fatresize > /dev/null 2>&1
echo Installing sysfsutils...
pacman --noconfirm --needed -S sysfsutils > /dev/null 2>&1
echo Installing usbutils...
pacman --noconfirm --needed -S usbutils > /dev/null 2>&1
echo Installing e2fsprogs...
pacman --noconfirm --needed -S e2fsprogs > /dev/null 2>&1
echo Installing inetutils...
pacman --noconfirm --needed -S inetutils > /dev/null 2>&1
echo Installing man-db...
pacman --noconfirm --needed -S man-db > /dev/null 2>&1
echo Installing man-pages...
pacman --noconfirm --needed -S man-pages > /dev/null 2>&1
echo All essential packages installed!
