#!/bin/bash
# poor man's package installation
echo Installing i3-gaps...
pacman --noconfirm --needed -S i3-gaps > /dev/null 2>&1
echo Installing xorg-server...
pacman --noconfirm --needed -S xorg-server > /dev/null 2>&1
echo Installing xorg-xwininfo...
pacman --noconfirm --needed -S xorg-xwininfo > /dev/null 2>&1
echo Installing xorg-xinit...
pacman --noconfirm --needed -S xorg-xinit > /dev/null 2>&1
echo Installing sxhkd...
pacman --noconfirm --needed -S sxhkd > /dev/null 2>&1
echo Installing ttf-inconsolata...
pacman --noconfirm --needed -S ttf-inconsolata > /dev/null 2>&1
echo Installing ttf-linux-libertine...
pacman --noconfirm --needed -S ttf-linux-libertine > /dev/null 2>&1
echo Installing ranger-git...
sudo -u $1 yay -S --noconfirm ranger-git > /dev/null 2>&1
echo Installing arandr...
pacman --noconfirm --needed -S arandr > /dev/null 2>&1
echo Installing bc...
pacman --noconfirm --needed -S bc > /dev/null 2>&1
echo Installing calcurse...
pacman --noconfirm --needed -S calcurse > /dev/null 2>&1
echo Installing xcompmgr...
pacman --noconfirm --needed -S xcompmgr > /dev/null 2>&1
echo Installing xorg-xprop...
pacman --noconfirm --needed -S xorg-xprop > /dev/null 2>&1
echo Installing dosfstools...
pacman --noconfirm --needed -S dosfstools > /dev/null 2>&1
echo Installing libnotify...
pacman --noconfirm --needed -S libnotify > /dev/null 2>&1
echo Installing dunst...
pacman --noconfirm --needed -S dunst > /dev/null 2>&1
echo Installing exfat-utils...
pacman --noconfirm --needed -S exfat-utils > /dev/null 2>&1
echo Installing sxiv...
pacman --noconfirm --needed -S sxiv > /dev/null 2>&1
echo Installing xwallpaper...
pacman --noconfirm --needed -S xwallpaper > /dev/null 2>&1
echo Installing ffmpeg...
pacman --noconfirm --needed -S ffmpeg > /dev/null 2>&1
echo Installing gnome-keyring...
pacman --noconfirm --needed -S gnome-keyring > /dev/null 2>&1
echo Installing gtk-theme-arc-gruvbox-git
sudo -u $1 yay -S --noconfirm gtk-theme-arc-gruvbox-git > /dev/null 2>&1
echo Installing neovim...
pacman --noconfirm --needed -S neovim > /dev/null 2>&1
echo Installing i3blocks...
pacman --noconfirm --needed -S i3blocks > /dev/null 2>&1
echo Installing mpd...
pacman --noconfirm --needed -S mpd > /dev/null 2>&1
echo Installing mpc...
pacman --noconfirm --needed -S mpc > /dev/null 2>&1
echo Installing mpv...
pacman --noconfirm --needed -S mpv > /dev/null 2>&1
echo Installing ncmpcpp...
pacman --noconfirm --needed -S ncmpcpp > /dev/null 2>&1
echo Installing newsboat...
pacman --noconfirm --needed -S newsboat > /dev/null 2>&1
echo Installing firefox...
pacman --noconfirm --needed -S firefox > /dev/null 2>&1
echo Installing ttf-joypixels...
pacman --noconfirm --needed -S ttf-joypixels > /dev/null 2>&1
echo Installing noto-fonts-emoji...
pacman --noconfirm --needed -S noto-fonts-emoji > /dev/null 2>&1
echo Installing ntfs-3g...
pacman --noconfirm --needed -S ntfs-3g > /dev/null 2>&1
echo Installing alsa-utils...
pacman --noconfirm --needed -S alsa-utils > /dev/null 2>&1
echo Installing se-im...
sudo -u $1 yay -S --noconfirm sc-im > /dev/null 2>&1
echo Installing maim...
pacman --noconfirm --needed -S maim > /dev/null 2>&1
echo Installing socat...
pacman --noconfirm --needed -S socat > /dev/null 2>&1
echo Installing tmux...
pacman --noconfirm --needed -S tmux > /dev/null 2>&1
echo Installing unclutter...
pacman --noconfirm --needed -S unclutter > /dev/null 2>&1
echo Installing unrar...
pacman --noconfirm --needed -S unrar > /dev/null 2>&1
echo Installing unzip...
pacman --noconfirm --needed -S unzip > /dev/null 2>&1
echo Installing lynx...
pacman --noconfirm --needed -S lynx > /dev/null 2>&1
echo Installing xcape...
pacman --noconfirm --needed -S xcape > /dev/null 2>&1
echo Installing xclip...
pacman --noconfirm --needed -S xclip > /dev/null 2>&1
echo Installing xdotool...
pacman --noconfirm --needed -S xdotool > /dev/null 2>&1
echo Installing xorg-xdpyinfo...
pacman --noconfirm --needed -S xorg-xdpyinfo > /dev/null 2>&1
echo Installing youtube-dl...
pacman --noconfirm --needed -S youtube-dl > /dev/null 2>&1
echo Installing zathura...
pacman --noconfirm --needed -S zathura > /dev/null 2>&1
echo Installing zathura-pdf-mupdf...
pacman --noconfirm --needed -S zathura-pdf-mupdf > /dev/null 2>&1
echo Installing python-ueberzug...
sudo -u $1 yay -S --noconfirm python-ueberzug > /dev/null 2>&1
echo Installing poppler...
pacman --noconfirm --needed -S poppler > /dev/null 2>&1
echo Installing mediainfo...
pacman --noconfirm --needed -S mediainfo > /dev/null 2>&1
echo Installing atool...
pacman --noconfirm --needed -S atool > /dev/null 2>&1
echo Installing fzf...
pacman --noconfirm --needed -S fzf > /dev/null 2>&1
echo Installing highlight...
pacman --noconfirm --needed -S highlight > /dev/null 2>&1
echo Installing xorg-xbacklight...
pacman --noconfirm --needed -S xorg-xbacklight > /dev/null 2>&1
echo Installing zsh-syntax-highlighting...
pacman --noconfirm --needed -S zsh-syntax-highlighting > /dev/null 2>&1
echo Installing task-spooler...
sudo -u $1 yay -S --noconfirm task-spooler  > /dev/null 2>&1
echo Installing simple-mtpfs...
sudo -u $1 yay -S --noconfirm simple-mtpfs > /dev/null 2>&1
echo Installing dmenu...
cd /tmp
dir=$(mktemp -d)
git clone --depth 1 "https://git.suckless.org/dmenu" "$dir" > /dev/null 2>&1
cd "$dir"
make > /dev/null 2>&1
make install > /dev/null 2>&1
cd /tmp
echo Installing st...
cd /tmp
dir=$(mktemp -d)
git clone --depth 1 "https://github.com/lukesmithxyz/st.git" "$dir" > /dev/null 2>&1
cd "$dir"
make > /dev/null 2>&1
make install > /dev/null 2>&1
cd /tmp
echo Installing slock...
pacman --noconfirm --needed -S slock > /dev/null 2>&1
echo All done!
